#!/usr/bin/env python3
"""
Today Celebrates — static site generator.

Pure function: holidays.json + a "today" date -> regenerated month data
files, per-holiday static pages, and sitemap.xml.

No Notion dependency. Reusable for the one-time Phase 3 run and for the
future Phase 4 daily cron (GitHub Actions pulls fresh Notion rows, writes
holidays.json, then calls this script).

Recurrence model:
  - "Annual" holidays have a fixed (month, day). Each generation run picks
    the NEXT occurrence of that (month, day) on or after `today`, rolling
    into next year if this year's date has already passed.
  - "Floating" holidays are computed per-year via a rule -- nth-weekday-of-
    month, last-weekday-of-month, an Easter offset, a fixed almanac/calendar
    lookup table (for astronomical or lunar/lunisolar events), or an offset
    relative to another holiday's date in this same dataset (e.g. Black
    Friday = Thanksgiving + 1 day) -- then the same next-occurrence-on-or-
    after-today logic is applied. See compute_floating_date() for the full
    list of rule kinds.

This means the site always shows each holiday's next upcoming occurrence
under its one permanent URL — no year in the slug, no duplicate pages per
year. A holiday whose date has already passed this year quietly rolls
forward to next year's date the next time the generator runs; that's the
"auto-recur" behavior confirmed with Jay for Phase 3.

Usage:
  python3 generate.py --holidays holidays.json --site /path/to/public --today 2026-09-13 [--dry-run]
"""
import argparse
import calendar
import datetime
import json
import os
import re
import sys

MONTH_NAMES = ["", "January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]
MONTH_ABBR = ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
              "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
WEEKDAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
                 "Saturday", "Sunday"]

SITE_BASE_URL = "https://todaycelebrates.com"

# First date to publish a /day/YYYY-MM-DD/ page for.
#
# Day pages are permanent URLs, so this is the archive's start line. Do not move
# it backwards casually: lowering it backfills dated pages for dates the site
# never actually covered, which is a deliberate content decision (and a
# near-duplicate-content risk), not a tweak. Moving it forward would orphan
# pages that are already published and indexed.
DAY_ARCHIVE_START = datetime.date(2026, 10, 8)

DEFAULT_TEMPLATES_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "templates"
)

# Ad slots on/off, and whether to label them.
#
# These are baked into the <html> class at build time rather than set by
# JavaScript on load, and that is the whole point: a deferred script adding the
# class after first paint makes every slot appear at once and shoves the page
# down, which is a measurable layout shift (0.09 CLS when it was done that way).
# Static class, no shift.
#
# ADS_ENABLED False removes all ad space from the site. It must agree with
# public/ads/house.js: this flag reserves the space, that file fills it.
ADS_ENABLED = True
ADS_LABELLED = False  # set True once real paid creative runs, not placeholders


def html_class():
    classes = []
    if ADS_ENABLED:
        classes.append("ads-enabled")
        if ADS_LABELLED:
            classes.append("ads-labelled")
    return " ".join(classes)


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

GENERATED_NOTE = (
    "<!-- Generated by scripts/generate.py from scripts/templates/index.html. "
    "Do not edit this file directly; your changes will be overwritten on the "
    "next run. -->"
)


def load_template(templates_dir, name):
    with open(os.path.join(templates_dir, name), encoding="utf-8") as f:
        return f.read()


def fill(template, values):
    """Replace every <!--TC:KEY--> marker in a template with its value.

    Marker substitution rather than str.format() on purpose: these templates are
    full of CSS and JS braces, and having to escape every one of them would be a
    reliable source of bugs (PAGE_TEMPLATE below does use .format(), which is
    exactly why its inline script needs doubled braces). Unfilled markers raise
    rather than shipping a visible HTML comment to the live site.
    """
    out = template
    for key, value in values.items():
        out = out.replace(f"<!--TC:{key}-->", value)
    # <!--TC-ONLY ... --> blocks are notes to whoever edits the template. Strip
    # them: they're maintainer context, not page content, and shipping them
    # would publish "edit this other file instead" to every visitor's view-source.
    out = re.sub(r"<!--TC-ONLY\b.*?-->\n?", "", out, flags=re.S)
    leftover = sorted(set(re.findall(r"<!--TC:([A-Z_0-9]+)-->", out)))
    if leftover:
        raise ValueError(f"template left unfilled markers: {leftover}")
    return out


# ---------------------------------------------------------------------------
# Date formatting (kept in one place so the baked homepage markup matches what
# index.html's own JS produces when it re-renders the same day)
# ---------------------------------------------------------------------------

def long_date(d):
    return f"{MONTH_NAMES[d.month]} {d.day}, {d.year}"


def month_day(d):
    return f"{MONTH_NAMES[d.month]} {d.day}"


def weekday_long_date(d):
    return f"{WEEKDAY_NAMES[d.weekday()]}, {MONTH_NAMES[d.month]} {d.day}, {d.year}"


def weekday_month_day(d):
    # Matches toLocaleDateString(undefined, {weekday:'long', month:'long', day:'numeric'})
    return f"{WEEKDAY_NAMES[d.weekday()]}, {MONTH_NAMES[d.month]} {d.day}"


def short_badge_date(d):
    # Matches toLocaleDateString(undefined, {month:'short', day:'numeric', year:'numeric'})
    return f"{MONTH_ABBR[d.month]} {d.day}, {d.year}"


def day_path(d):
    return f"/day/{d.isoformat()}/"


def js_day_key(d):
    # index.html's own key() format: unpadded, e.g. "2026-10-9"
    return f"{d.year}-{d.month}-{d.day}"


def plural(n, singular, plural_form=None):
    return singular if n == 1 else (plural_form or singular + "s")


def join_names(names):
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return f"{names[0]} and {names[1]}"
    return ", ".join(names[:-1]) + f" and {names[-1]}"


# ---------------------------------------------------------------------------
# Date computation
# ---------------------------------------------------------------------------

def nth_weekday_of_month(year, month, weekday, n):
    """weekday: 0=Monday ... 6=Sunday (Python's convention). n: 1-based."""
    first = datetime.date(year, month, 1)
    first_weekday = first.weekday()
    offset = (weekday - first_weekday) % 7
    day = 1 + offset + (n - 1) * 7
    days_in_month = calendar.monthrange(year, month)[1]
    if day > days_in_month:
        raise ValueError(f"nth_weekday_of_month: no {n}th weekday {weekday} in {year}-{month:02d}")
    return datetime.date(year, month, day)


def labor_day(year):
    return nth_weekday_of_month(year, 9, 0, 1)  # 1st Monday of September


def last_weekday_of_month(year, month, weekday):
    """weekday: 0=Monday ... 6=Sunday. The LAST occurrence of that weekday in the month."""
    days_in_month = calendar.monthrange(year, month)[1]
    last = datetime.date(year, month, days_in_month)
    offset = (last.weekday() - weekday) % 7
    return last - datetime.timedelta(days=offset)


def nearest_weekday_to(year, month, day, weekday):
    """The occurrence of `weekday` nearest to the fixed calendar date (year, month, day).
    Searches +/- 3 days, which always finds exactly one match since weekdays cycle
    every 7 days. Used for holidays defined as e.g. "the Sunday closest to Nov 30"."""
    anchor = datetime.date(year, month, day)
    for delta in (0, 1, -1, 2, -2, 3, -3):
        candidate = anchor + datetime.timedelta(days=delta)
        if candidate.weekday() == weekday:
            return candidate
    raise RuntimeError(f"nearest_weekday_to: no match found near {anchor}")  # unreachable


def last_weekday_on_or_before(date, weekday):
    """The most recent occurrence of `weekday` on or before `date`."""
    offset = (date.weekday() - weekday) % 7
    return date - datetime.timedelta(days=offset)


def last_weekday_before(date, weekday):
    """The most recent occurrence of `weekday` strictly before `date`."""
    return last_weekday_on_or_before(date - datetime.timedelta(days=1), weekday)


def us_election_day(year):
    """US General Election Day: the Tuesday after the first Monday in November."""
    first_monday = nth_weekday_of_month(year, 11, 0, 1)
    return first_monday + datetime.timedelta(days=1)


def easter_sunday(year):
    """Western/Gregorian Easter Sunday, via the Anonymous Gregorian algorithm
    (Computus). Deterministic — no lookup table needed, valid for any Gregorian
    year. See https://en.wikipedia.org/wiki/Date_of_Easter#Anonymous_Gregorian_algorithm"""
    a = year % 19
    b = year // 100
    c = year % 100
    d = b // 4
    e = b % 4
    f = (b + 8) // 25
    g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30
    i = c // 4
    k = c % 4
    l = (32 + 2 * e + 2 * i - h - k) % 7
    m = (a + 11 * h + 22 * l) // 451
    month = (h + l - 7 * m + 114) // 31
    day = ((h + l - 7 * m + 114) % 31) + 1
    return datetime.date(year, month, day)


def next_friday_the_13th(after_date):
    """The first Friday the 13th on or after `after_date`. A calendar year can
    have zero to three of these, so — unlike every other rule here — this
    can't be computed "for a given year" and is special-cased in
    next_occurrence() instead of going through compute_floating_date()."""
    candidate = after_date
    for _ in range(400):  # generous bound; a match is always within a few months
        if candidate.day == 13 and candidate.weekday() == 4:
            return candidate
        candidate += datetime.timedelta(days=1)
    raise RuntimeError("could not find next Friday the 13th within 400 days")


def compute_floating_date(rule, year, by_slug=None, memo=None, in_progress=None):
    kind = rule["rule"]
    if kind == "nth_weekday":
        return nth_weekday_of_month(year, rule["month"], rule["weekday"], rule["n"])
    if kind == "after_labor_day_sunday":
        ld = labor_day(year)
        # first Sunday after Labor Day (Labor Day is always a Monday, so +6 days)
        return ld + datetime.timedelta(days=6)
    if kind == "lookup_table":
        table = rule["table"]
        key = str(year)  # JSON round-trips int keys as strings
        if key not in table:
            raise ValueError(
                f"lookup_table has no hand-confirmed date for {year} (it covers "
                f"{min(table)}-{max(table)}) — add the year after checking an almanac "
                f"or the organizing body, don't guess or extrapolate."
            )
        mm, dd = table[key].split("-")
        return datetime.date(year, int(mm), int(dd))
    if kind == "last_weekday":
        return last_weekday_of_month(year, rule["month"], rule["weekday"])
    if kind == "last_weekday_offset":
        base = last_weekday_of_month(year, rule["month"], rule["weekday"])
        return base + datetime.timedelta(days=rule["offset_days"])
    if kind == "easter_offset":
        return easter_sunday(year) + datetime.timedelta(days=rule["days"])
    if kind == "us_election_day":
        return us_election_day(year)
    if kind == "nearest_weekday_to_date":
        return nearest_weekday_to(year, rule["month"], rule["day"], rule["weekday"])
    if kind == "last_weekday_before_date":
        anchor = datetime.date(year, rule["month"], rule["day"])
        return last_weekday_before(anchor, rule["weekday"])
    if kind == "offset_from_slug":
        if by_slug is None or memo is None:
            raise ValueError("offset_from_slug rule requires by_slug/memo context")
        ref = by_slug.get(rule["slug"])
        if ref is None:
            raise ValueError(f"offset_from_slug: unknown reference slug {rule['slug']!r}")
        ref_date = holiday_date_for_year(ref, year, by_slug, memo, in_progress)
        return ref_date + datetime.timedelta(days=rule["days"])
    if kind == "last_weekday_before_slug":
        if by_slug is None or memo is None:
            raise ValueError("last_weekday_before_slug rule requires by_slug/memo context")
        ref = by_slug.get(rule["slug"])
        if ref is None:
            raise ValueError(f"last_weekday_before_slug: unknown reference slug {rule['slug']!r}")
        ref_date = holiday_date_for_year(ref, year, by_slug, memo, in_progress)
        return last_weekday_on_or_before(ref_date, rule["weekday"])
    raise ValueError(f"unknown floating rule kind: {kind}")


def holiday_date_for_year(holiday, year, by_slug, memo, in_progress=None):
    """Resolve a holiday's date for one specific calendar year (not "next
    occurrence" — an exact year). Needed because some floating rules
    (offset_from_slug, last_weekday_before_slug) are defined relative to
    another holiday in the dataset and must recursively resolve that
    holiday's date for the same year first. Memoized on (slug, year); guards
    against a rule cycle (A defined relative to B defined relative to A)."""
    slug = holiday["slug"]
    key = (slug, year)
    if key in memo:
        return memo[key]
    if in_progress is None:
        in_progress = set()
    if key in in_progress:
        raise RuntimeError(f"circular floating-rule reference involving {slug!r} for {year}")
    in_progress.add(key)
    try:
        if holiday["recurrence"] == "Annual":
            result = datetime.date(year, holiday["month"], holiday["day"])
        elif holiday["recurrence"] == "Floating":
            rule = holiday["floating_rule"]
            result = compute_floating_date(rule, year, by_slug=by_slug, memo=memo, in_progress=in_progress)
        else:
            raise ValueError(f"unknown recurrence type: {holiday['recurrence']!r} for {slug}")
    finally:
        in_progress.discard(key)
    memo[key] = result
    return result


def next_occurrence(holiday, today, by_slug=None, memo=None):
    """Return the date.date of this holiday's next occurrence on/after `today`."""
    if holiday["recurrence"] == "Annual":
        month, day = holiday["month"], holiday["day"]
        for year in (today.year, today.year + 1):
            try:
                candidate = datetime.date(year, month, day)
            except ValueError:
                continue  # e.g. Feb 29 in a non-leap year, not expected in this dataset
            if candidate >= today:
                return candidate
        # Shouldn't happen (year+1 always covers it), but fail loud rather than silent.
        raise RuntimeError(f"could not find next occurrence for {holiday['slug']}")
    elif holiday["recurrence"] == "Floating":
        rule = holiday["floating_rule"]
        if rule["rule"] == "next_friday_13":
            # Can produce 0-3 hits per calendar year, so it can't be resolved
            # "for a given year" like every other rule — scan forward directly.
            return next_friday_the_13th(today)
        if by_slug is None:
            by_slug = {}
        if memo is None:
            memo = {}
        for year in (today.year, today.year + 1):
            candidate = holiday_date_for_year(holiday, year, by_slug, memo)
            if candidate >= today:
                return candidate
        raise RuntimeError(f"could not find next floating occurrence for {holiday['slug']}")
    else:
        raise ValueError(f"unknown recurrence type: {holiday['recurrence']!r} for {holiday['slug']}")


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

PAGE_TEMPLATE = """<!doctype html>
<html lang="en" class="{html_class}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WNN6PH0QNC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){{dataLayer.push(arguments);}}
  gtag('js', new Date());

  gtag('config', 'G-WNN6PH0QNC');
</script>
<title>{name} — {date_long} | Today Celebrates</title>
<meta name="description" content="{description}">
<link rel="canonical" href="{url}">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.webmanifest">
<meta name="theme-color" content="#ff6b45" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#ff8a63" media="(prefers-color-scheme: dark)">
<meta property="og:type" content="article">
<meta property="og:title" content="{name} — {date_long}">
<meta property="og:description" content="{description}">
<meta property="og:image" content="{image}">
<meta property="og:url" content="{url}">
<meta property="og:site_name" content="Today Celebrates">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{name} — {date_long}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="{image}">
<link rel="stylesheet" href="/styles/holiday.css">
<link rel="stylesheet" href="/styles/ads.css">
<script type="application/ld+json">{ld_json}</script>
</head>
<body>
  <div class="topbar"><a href="/">Today Celebrates</a></div>
  <div class="hero" style="background-image:url('{image}')">
    <div class="hero-inner">
      <div class="hero-date">{date_long}</div>
      <h1>{name}</h1>
    </div>
  </div>
  <div class="page-grid">
  <main>
    <div class="ad-slot ad-leaderboard" data-ad-slot="leaderboard" data-ad-eager="1"></div>
    <span class="category-tag">{category_title}</span>
    <p class="desc">{description}</p>
    <div class="ad-slot ad-rect" data-ad-slot="incontent"></div>
    <a class="back-link" href="{day_link}">&larr; See everything else {date_short} celebrates</a>
    <div class="also">Know a holiday we're missing, or think this date has more going on? Today Celebrates tracks daily national, international, and world observances all year.</div>
    <div class="ad-slot ad-rect" data-ad-slot="footer"></div>
  </main>
  <aside class="ad-rail" data-ad-slot="rail"></aside>
  </div>
  <footer>Today Celebrates — a daily calendar of national &amp; international holidays.</footer>
  <script src="/ads/house.js" defer></script>
  <script src="/ads/slots.js" defer></script>
</body>
</html>
"""


def esc_attr(s):
    # Matches the escaping convention already baked into the live pages
    # (BeautifulSoup's default serialization), including apostrophes as
    # &#x27; — needed so unchanged holidays regenerate byte-identical.
    return (s.replace("&", "&amp;").replace('"', "&quot;")
             .replace("<", "&lt;").replace(">", "&gt;")
             .replace("'", "&#x27;"))


def render_page(holiday, occ_date, day_link="/"):
    slug = holiday["slug"]
    name = holiday["name"]
    category = holiday["category"]
    description = holiday["description"]
    url = f"{SITE_BASE_URL}/holiday/{slug}/"
    image = f"/images/hero/{category}.jpg"
    iso_date = occ_date.isoformat()
    date_long = f"{MONTH_NAMES[occ_date.month]} {occ_date.day}, {occ_date.year}"
    date_short = f"{MONTH_NAMES[occ_date.month]} {occ_date.day}"

    ld = {
        "@context": "https://schema.org",
        "@type": "Event",
        "name": name,
        "description": description,
        "startDate": iso_date,
        "endDate": iso_date,
        "eventStatus": "https://schema.org/EventScheduled",
        "eventAttendanceMode": "https://schema.org/OnlineEventAttendanceMode",
        "location": {"@type": "VirtualLocation", "url": url},
        "organizer": {"@type": "Organization", "name": "Today Celebrates", "url": f"{SITE_BASE_URL}/"},
        "image": [image],
        "url": url,
    }
    ld_json = json.dumps(ld, ensure_ascii=False).replace("</", "<\\/")

    return PAGE_TEMPLATE.format(
        name=esc_attr(name),
        date_long=date_long,
        date_short=date_short,
        description=esc_attr(description),
        url=url,
        image=image,
        category_title=category.capitalize() if category != "lgbt" else category.upper(),
        ld_json=ld_json,
        day_link=day_link,
        html_class=html_class(),
    )


# ---------------------------------------------------------------------------
# Main generation
# ---------------------------------------------------------------------------

def build_day_index(holidays, by_slug, memo, start, end):
    """Map every date in [start, end] to the holidays observed on that date.

    This is the opposite question from next_occurrence(): absolute ("what falls
    on this exact date") rather than relative ("what's next"). A dated,
    permanent page needs the absolute answer.

    Deliberately derived only from the holiday data and the date itself -- never
    from "today" -- so any given date renders byte-identically on every run.
    That's what lets the archive be regenerated every day without churning git
    or drifting out of sync with the site's chrome.

    Returns (index, skipped_slugs).
    """
    index = {}
    skipped = set()
    if end < start:
        return index, sorted(skipped)

    for h in holidays:
        rule = h.get("floating_rule") or {}
        if rule.get("rule") == "next_friday_13":
            # 0-3 per calendar year, so it has no single date per year like
            # every other rule: it belongs on every Friday the 13th in range.
            d = start
            while d <= end:
                if d.day == 13 and d.weekday() == 4:
                    index.setdefault(d, []).append(h)
                d += datetime.timedelta(days=1)
            continue

        for year in range(start.year, end.year + 1):
            try:
                occ = holiday_date_for_year(h, year, by_slug, memo)
            except (ValueError, RuntimeError, KeyError):
                # Same graceful-degradation stance as next_occurrence: one
                # unresolvable rule must not take out the whole archive. The
                # holiday is simply absent from that year's dated pages.
                skipped.add(h["slug"])
                continue
            if start <= occ <= end:
                index.setdefault(occ, []).append(h)

    for d in index:
        index[d].sort(key=lambda h: (h.get("display_order", 999), h["name"]))
    return index, sorted(skipped)


def moveable_note_html(date, items, by_slug, memo):
    """The genuinely year-specific part of a dated page.

    Which observances landed on this exact date because of a rule rather than a
    fixed calendar date, and where the same observance lands the year after.
    That difference -- plus the weekday -- is what actually distinguishes
    October 9, 2026 from October 9, 2027, so it's worth stating outright rather
    than publishing two pages that read identically.
    """
    lines = []
    f13_slugs = {
        h["slug"] for h in items
        if (h.get("floating_rule") or {}).get("rule") == "next_friday_13"
    }
    moveable = [h for h in items
                if h["recurrence"] == "Floating" and h["slug"] not in f13_slugs]

    by_next_date = {}
    for h in moveable:
        try:
            nxt = holiday_date_for_year(h, date.year + 1, by_slug, memo)
        except (ValueError, RuntimeError, KeyError):
            continue  # rule can't reach next year yet -- don't claim a date
        by_next_date.setdefault(nxt, []).append(h["name"])

    for nxt, names in sorted(by_next_date.items()):
        one = len(names) == 1
        lines.append(
            f"{esc_attr(join_names(names))} {'falls' if one else 'fall'} on this date "
            f"in {date.year} because {'it is' if one else 'they are'} set by a rule "
            f"rather than a fixed date &mdash; in {nxt.year}, "
            f"{'it lands' if one else 'they land'} on {esc_attr(month_day(nxt))}."
        )

    if f13_slugs:
        lines.append(
            f"Friday the 13th lands here because the 13th of "
            f"{MONTH_NAMES[date.month]} falls on a Friday in {date.year}."
        )

    if not lines:
        return ""
    body = "".join(f"<p>{line}</p>" for line in lines)
    return f'<div class="moveable-note">{body}</div>'


def render_day_page(date, items, prev_date, next_date, template, by_slug, memo):
    """Render one permanent /day/YYYY-MM-DD/ page."""
    n = len(items)
    lead = items[0]
    hero_rel = f"/images/hero/{lead['category']}.jpg"
    url = f"{SITE_BASE_URL}{day_path(date)}"

    rows = []
    for i, h in enumerate(items):
        lead_tag = '<span class="lead-tag">Leading</span>' if i == 0 else ""
        rows.append(
            f'<li><a href="/holiday/{h["slug"]}/">{esc_attr(h["name"])}</a>'
            f'<span class="cat">{esc_attr(h["category"])}</span>{lead_tag}</li>'
        )

    # A rectangle partway down a long list is the conventional (and
    # highest-viewability) in-content position for a list page. Split the list
    # rather than putting an ad inside an <li>, and resume the numbering with
    # start= so the ad doesn't renumber the observances.
    if len(rows) >= 8:
        split = 5
        list_block = (
            f'<ol class="day-list">{"".join(rows[:split])}</ol>'
            f'<div class="ad-slot ad-rect" data-ad-slot="incontent"></div>'
            f'<ol class="day-list" start="{split + 1}">{"".join(rows[split:])}</ol>'
        )
    else:
        list_block = f'<ol class="day-list">{"".join(rows)}</ol>'

    preview = join_names([h["name"] for h in items[:3]])
    description = (
        f"{n} national and international {plural(n, 'holiday')} and observances "
        f"fall on {weekday_long_date(date)}, including {preview}."
    )

    ld = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": f"Holidays and observances on {long_date(date)}",
        "numberOfItems": n,
        "itemListOrder": "https://schema.org/ItemListOrderAscending",
        "url": url,
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": i + 1,
                "name": h["name"],
                "url": f"{SITE_BASE_URL}/holiday/{h['slug']}/",
            }
            for i, h in enumerate(items)
        ],
    }
    ld_json = json.dumps(ld, ensure_ascii=False).replace("</", "<\\/")

    nav = []
    nav.append(
        f'<a href="{day_path(prev_date)}">&larr; {esc_attr(long_date(prev_date))}</a>'
        if prev_date else "<span></span>"
    )
    nav.append(
        f'<a href="{day_path(next_date)}">{esc_attr(long_date(next_date))} &rarr;</a>'
        if next_date else "<span></span>"
    )

    return fill(template, {
        "TITLE": esc_attr(
            f"{weekday_long_date(date)}: {n} {plural(n, 'Holiday')} & Observances "
            f"| Today Celebrates"
        ),
        "OG_TITLE": esc_attr(f"Everything {long_date(date)} celebrates"),
        "DESCRIPTION": esc_attr(description),
        "URL": url,
        "HERO_IMAGE": hero_rel,
        # og:image/twitter:image want an absolute URL -- several scrapers won't
        # resolve a site-relative one.
        "HERO_IMAGE_ABS": f"{SITE_BASE_URL}{hero_rel}",
        "WEEKDAY_LINE": esc_attr(weekday_long_date(date)).upper(),
        "HEADLINE": esc_attr(f"Everything {long_date(date)} celebrates"),
        "INTRO": (
            f"{n} national, international, and world {plural(n, 'observance')} "
            f"{plural(n, 'is', 'are')} on the calendar for "
            f"{esc_attr(weekday_long_date(date))}."
        ),
        "LIST_BLOCK": list_block,
        "MOVEABLE_NOTE": moveable_note_html(date, items, by_slug, memo),
        "DAY_NAV": "".join(nav),
        "HTML_CLASS": html_class(),
        "DATE_PLAIN": esc_attr(long_date(date)),
        "LD_JSON": ld_json,
    })


def render_home(date, items, template, has_day_page):
    """Render public/index.html with the generator's "today" baked in.

    The baked markup must match what index.html's own renderHero/renderList
    produce for the same day, because that script re-renders these same elements
    as soon as it loads. Matching means no flash of changing content; the point
    of baking it is that a crawler (or a visitor with JS blocked) sees the real
    holiday names instead of empty placeholders.
    """
    n = len(items)
    day_link = (
        f'<a href="{day_path(date)}">Permanent page for {esc_attr(long_date(date))} &rarr;</a>'
        if has_day_page else ""
    )

    if not items:
        # Mirrors the script's own empty state.
        return fill(template, {
            # Literal em dash, not &mdash; -- these strings go through
            # esc_attr(), which would turn the entity's & into &amp; and print
            # it verbatim on the page.
            "HTML_CLASS": html_class(),
            "GENERATED_NOTE": GENERATED_NOTE,
            "TITLE": esc_attr(f"Today Celebrates — {long_date(date)}"),
            "DESCRIPTION": esc_attr(
                "A daily calendar of national, international, and world holidays "
                "and observances."
            ),
            "TODAY_KEY": js_day_key(date),
            "HERO_IMAGE": "/images/hero/celebration.jpg",
            "HERO_BADGE": esc_attr(short_badge_date(date)),
            "HERO_EYEBROW": "No data yet",
            "HERO_HEADLINE": esc_attr(weekday_month_day(date)),
            "HERO_SUB": "No holidays logged for this day yet.",
            "CAL_LABEL": esc_attr(f"{MONTH_NAMES[date.month]} {date.year}"),
            "LIST_TITLE": esc_attr(f"Everything {weekday_month_day(date)} celebrates"),
            "LIST_SUB": "",
            "CHIPS": '<div class="empty-note">No holidays logged for this day yet.</div>',
            "DAY_LINK": day_link,
        })

    lead = items[0]
    rest = n - 1
    chips = "".join(
        f'<a class="chip{" lead" if i == 0 else ""}" '
        f'href="/holiday/{h["slug"]}/">{esc_attr(h["name"])}</a>'
        for i, h in enumerate(items)
    )
    hero_sub = (
        f"Plus {rest} more {plural(rest, 'celebration')} on {esc_attr(month_day(date))}."
        if rest > 0
        else f"The only celebration on the calendar for {esc_attr(month_day(date))}."
    )
    preview = join_names([h["name"] for h in items[:3]])

    return fill(template, {
        "HTML_CLASS": html_class(),
        "GENERATED_NOTE": GENERATED_NOTE,
        "TITLE": esc_attr(
            f"What Holiday Is Today? — {long_date(date)} | Today Celebrates"
        ),
        "DESCRIPTION": esc_attr(
            f"{n} {plural(n, 'holiday')} and observances today, "
            f"{weekday_long_date(date)}: {preview}. A daily calendar of national, "
            f"international, and world holidays."
        ),
        "TODAY_KEY": js_day_key(date),
        "HERO_IMAGE": f"/images/hero/{lead['category']}.jpg",
        "HERO_BADGE": esc_attr(short_badge_date(date)),
        "HERO_EYEBROW": "Today's leading celebration",
        "HERO_HEADLINE": f'<a href="/holiday/{lead["slug"]}/">{esc_attr(lead["name"])}</a>',
        "HERO_SUB": hero_sub,
        "CAL_LABEL": esc_attr(f"{MONTH_NAMES[date.month]} {date.year}"),
        "LIST_TITLE": esc_attr(f"Everything {weekday_month_day(date)} celebrates"),
        "LIST_SUB": f"{n} {plural(n, 'celebration')} on the calendar.",
        "CHIPS": chips,
        "DAY_LINK": day_link,
    })


def read_sitemap_lastmods(path):
    """Parse an existing sitemap.xml into {loc: lastmod}.

    Returns {} when the file is missing or unparseable -- an absent or broken
    sitemap should degrade to "stamp everything with today", never a crash.
    This is deliberately a regex rather than an XML parse: the only sitemap
    this ever reads is the one render below writes, one <url> per line.
    """
    try:
        with open(path, encoding="utf-8") as f:
            xml = f.read()
    except OSError:
        return {}
    pairs = re.findall(
        r"<loc>\s*([^<]+?)\s*</loc>\s*<lastmod>\s*([^<]+?)\s*</lastmod>", xml
    )
    return dict(pairs)


def generate(holidays, today, site_dir, dry_run=False, templates_dir=None):
    """Returns a report dict describing what changed."""
    templates_dir = templates_dir or DEFAULT_TEMPLATES_DIR
    by_slug = {h["slug"]: h for h in holidays}
    memo = {}  # (slug, year) -> date.date, shared across all holidays this run
    occurrences = {}  # slug -> date.date
    unresolved = []   # holidays whose rule could not produce a date this run
    for h in holidays:
        try:
            occurrences[h["slug"]] = next_occurrence(h, today, by_slug, memo)
        except (ValueError, RuntimeError, KeyError) as e:
            # One unresolvable holiday must never take the whole run down with
            # it. The overwhelmingly likely cause is a lookup_table in
            # export_from_notion.py that has run out of hand-confirmed years
            # (see scripts/README.md) -- and if that aborted generation, the
            # daily workflow would start failing and the entire site would
            # silently stop rolling holidays forward. So skip just this one:
            # its existing page and sitemap entry are left untouched, it drops
            # out of the calendar's month data until its rule is extended, and
            # everything else regenerates normally. main() warns loudly.
            unresolved.append({"slug": h["slug"], "name": h["name"], "error": str(e)})

    # ---- month data files: only for months that actually have content ----
    by_month = {}  # "YYYY-MM" -> { "YYYY-M-D": [(order, name), ...] }
    for h in holidays:
        if h["slug"] not in occurrences:
            continue  # unresolved: can't place it on a calendar day
        occ = occurrences[h["slug"]]
        mk = f"{occ.year:04d}-{occ.month:02d}"
        dk = f"{occ.year}-{occ.month}-{occ.day}"
        # Preserve each holiday's original display position within its day
        # (captured from the live site at Phase 3 build time) rather than
        # re-sorting alphabetically, so unaffected days stay byte-identical
        # and the deliberate Notion ordering survives regeneration.
        by_month.setdefault(mk, {}).setdefault(dk, []).append(
            (h.get("display_order", 999), h["name"])
        )

    for mk, days in by_month.items():
        for dk in days:
            days[dk].sort(key=lambda pair: pair[0])
            days[dk] = [name for _, name in days[dk]]

    data_dir = os.path.join(site_dir, "data")
    existing_month_files = set()
    if os.path.isdir(data_dir):
        existing_month_files = {f[:-5] for f in os.listdir(data_dir) if f.endswith(".json")}

    month_diffs = {}
    for mk, days in sorted(by_month.items()):
        path = os.path.join(data_dir, f"{mk}.json")
        new_content = json.dumps(days, ensure_ascii=False, separators=(",", ":"))
        old_content = None
        if os.path.exists(path):
            old_content = open(path, encoding="utf-8").read()
        if old_content != new_content:
            month_diffs[mk] = {"old_days": len(json.loads(old_content)) if old_content else 0,
                                "new_days": len(days)}
        if not dry_run:
            os.makedirs(data_dir, exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(new_content)

    stale_month_files = existing_month_files - set(by_month.keys())

    # ---- /day/YYYY-MM-DD/ permanent dated pages ----
    # The index runs from min(archive start, today) so "today" is always in it
    # even when generating for a date before the archive opened, but only dates
    # from DAY_ARCHIVE_START onward get published as pages.
    day_end = max(occurrences.values()) if occurrences else today
    day_index, day_index_skipped = build_day_index(
        holidays, by_slug, memo, min(DAY_ARCHIVE_START, today), day_end
    )
    day_dates = [d for d in sorted(day_index) if d >= DAY_ARCHIVE_START]

    day_template = load_template(templates_dir, "day.html")
    day_diffs = {"created": [], "changed": [], "unchanged": 0}
    for i, d in enumerate(day_dates):
        prev_d = day_dates[i - 1] if i > 0 else None
        next_d = day_dates[i + 1] if i + 1 < len(day_dates) else None
        new_html = render_day_page(
            d, day_index[d], prev_d, next_d, day_template, by_slug, memo
        )
        page_dir = os.path.join(site_dir, "day", d.isoformat())
        page_path = os.path.join(page_dir, "index.html")
        old_html = open(page_path, encoding="utf-8").read() if os.path.exists(page_path) else None
        if old_html is None:
            day_diffs["created"].append(d.isoformat())
        elif old_html != new_html:
            day_diffs["changed"].append(d.isoformat())
        else:
            day_diffs["unchanged"] += 1
        if not dry_run:
            os.makedirs(page_dir, exist_ok=True)
            with open(page_path, "w", encoding="utf-8") as f:
                f.write(new_html)

    published_days = set(day_dates)

    # ---- per-holiday pages ----
    page_diffs = {"changed": [], "unchanged": [], "created": [], "skipped": []}
    for h in holidays:
        slug = h["slug"]
        if slug not in occurrences:
            # Unresolvable date: leave whatever page already exists exactly as
            # it is. A stale date on one page beats deleting it or writing a
            # dateless one.
            page_diffs["skipped"].append(slug)
            continue
        occ = occurrences[slug]
        # Point the back-link at the dated page for this holiday's occurrence
        # rather than the homepage -- that's the page that actually answers
        # "what else is on this date". Falls back to / if that day isn't
        # published (a date before the archive opened).
        day_link = day_path(occ) if occ in published_days else "/"
        new_html = render_page(h, occ, day_link)
        page_dir = os.path.join(site_dir, "holiday", slug)
        page_path = os.path.join(page_dir, "index.html")
        old_html = None
        if os.path.exists(page_path):
            old_html = open(page_path, encoding="utf-8").read()
        if old_html is None:
            page_diffs["created"].append(slug)
        elif old_html != new_html:
            page_diffs["changed"].append(slug)
        else:
            page_diffs["unchanged"].append(slug)
        if not dry_run:
            os.makedirs(page_dir, exist_ok=True)
            with open(page_path, "w", encoding="utf-8") as f:
                f.write(new_html)

    # ---- homepage: today's content baked into the HTML ----
    home_items = day_index.get(today, [])
    home_html = render_home(
        today,
        home_items,
        load_template(templates_dir, "index.html"),
        has_day_page=today in published_days,
    )
    home_path = os.path.join(site_dir, "index.html")
    old_home = open(home_path, encoding="utf-8").read() if os.path.exists(home_path) else None
    home_changed = old_home != home_html
    if not dry_run:
        with open(home_path, "w", encoding="utf-8") as f:
            f.write(home_html)

    # ---- sitemap.xml ----
    # lastmod must say when a page's content actually changed, not when the
    # generator last ran. Stamping every URL with today's date on every run
    # told crawlers all ~2,400 pages changed daily when ~10 did -- a
    # misleading crawl signal, and a 4,880-line diff in every daily commit.
    # So: carry each URL's lastmod forward from the sitemap already on disk,
    # and only stamp today on pages this run actually created or changed. A
    # URL with no previous entry (first run, brand-new holiday) gets today.
    today_iso = today.isoformat()
    previous_lastmod = read_sitemap_lastmods(os.path.join(site_dir, "sitemap.xml"))
    touched = set(page_diffs["created"]) | set(page_diffs["changed"])

    def lastmod_for(loc, changed_this_run):
        if changed_this_run:
            return today_iso
        return previous_lastmod.get(loc, today_iso)

    home_loc = f"{SITE_BASE_URL}/"
    urls = [
        f'  <url><loc>{home_loc}</loc>'
        f'<lastmod>{lastmod_for(home_loc, home_changed)}</lastmod></url>'
    ]

    # Dated pages. Past ones are regenerated byte-identically, so they keep the
    # lastmod they were first published with -- which is the truth about them.
    touched_days = set(day_diffs["created"]) | set(day_diffs["changed"])
    for d in day_dates:
        loc = f"{SITE_BASE_URL}{day_path(d)}"
        urls.append(
            f'  <url><loc>{loc}</loc>'
            f'<lastmod>{lastmod_for(loc, d.isoformat() in touched_days)}</lastmod></url>'
        )

    for h in sorted(holidays, key=lambda h: h["slug"]):
        slug = h["slug"]
        if slug not in occurrences and not os.path.exists(
            os.path.join(site_dir, "holiday", slug, "index.html")
        ):
            # Unresolvable date AND no page was ever generated -- don't
            # advertise a URL that would 404.
            continue
        loc = f"{SITE_BASE_URL}/holiday/{slug}/"
        urls.append(
            f'  <url><loc>{loc}</loc>'
            f'<lastmod>{lastmod_for(loc, slug in touched)}</lastmod></url>'
        )
    sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
               '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
               + "\n".join(urls) + "\n</urlset>\n")
    sitemap_path = os.path.join(site_dir, "sitemap.xml")
    old_sitemap = open(sitemap_path, encoding="utf-8").read() if os.path.exists(sitemap_path) else None
    sitemap_changed = old_sitemap != sitemap
    if not dry_run:
        with open(sitemap_path, "w", encoding="utf-8") as f:
            f.write(sitemap)

    return {
        "today": today_iso,
        "months_covered": sorted(by_month.keys()),
        "month_diffs": month_diffs,
        "stale_month_files": sorted(stale_month_files),
        "pages_created": sorted(page_diffs["created"]),
        "pages_changed": sorted(page_diffs["changed"]),
        "pages_unchanged_count": len(page_diffs["unchanged"]),
        "pages_skipped": sorted(page_diffs["skipped"]),
        "unresolved_holidays": sorted(unresolved, key=lambda u: u["slug"]),
        "home_changed": home_changed,
        "day_pages_total": len(day_dates),
        "day_pages_created": day_diffs["created"],
        "day_pages_changed": day_diffs["changed"],
        "day_pages_unchanged_count": day_diffs["unchanged"],
        "day_index_skipped": day_index_skipped,
        "sitemap_changed": sitemap_changed,
        "occurrences": {slug: d.isoformat() for slug, d in occurrences.items()},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--holidays", required=True, help="path to holidays.json")
    ap.add_argument("--site", required=True, help="path to the site's public/ directory")
    ap.add_argument("--today", required=True, help="YYYY-MM-DD, the generation run's 'today'")
    ap.add_argument("--dry-run", action="store_true", help="compute + report only, write nothing")
    ap.add_argument("--report", help="optional path to write the JSON report to")
    ap.add_argument("--templates", default=DEFAULT_TEMPLATES_DIR,
                    help="directory holding index.html and day.html templates "
                         "(default: scripts/templates/ next to this script)")
    args = ap.parse_args()

    holidays = json.load(open(args.holidays, encoding="utf-8"))
    today = datetime.date.fromisoformat(args.today)

    report = generate(holidays, today, args.site, dry_run=args.dry_run,
                      templates_dir=args.templates)

    print(json.dumps(
        {k: v for k, v in report.items() if k != "occurrences"},
        indent=2, ensure_ascii=False
    ))

    # Loud warning for the one failure mode that would otherwise rot quietly:
    # a floating rule that can no longer produce a date. The run still
    # succeeds -- the rest of the site regenerates and commits -- but these
    # holidays are frozen out of the calendar until their rule is extended.
    unresolved = report["unresolved_holidays"]
    for u in unresolved:
        print(
            f"WARNING: {u['name']!r} ({u['slug']}) has no resolvable date and was "
            f"skipped -- it is missing from the calendar until this is fixed. "
            f"Cause: {u['error']}",
            file=sys.stderr,
        )
    if unresolved:
        print(
            f"WARNING: {len(unresolved)} holiday(s) skipped this run. This is "
            f"almost always a lookup_table in scripts/export_from_notion.py that "
            f"has run out of hand-confirmed years -- see scripts/README.md.",
            file=sys.stderr,
        )
        # When running in GitHub Actions, also emit a workflow command so this
        # surfaces as a visible warning annotation on the run summary instead
        # of being buried in the log. Guarded on GITHUB_ACTIONS so the "::"
        # syntax stays out of the way when run by hand. Keeping this here
        # rather than in the workflow YAML means the daily automation needs no
        # changes to pick it up.
        if os.environ.get("GITHUB_ACTIONS") == "true":
            slugs = ", ".join(u["slug"] for u in unresolved)
            print(
                f"::warning title=Holiday dates need attention::{len(unresolved)} "
                f"holiday(s) skipped this run and are missing from the calendar: "
                f"{slugs}. Most likely an expired lookup_table year in "
                f"scripts/export_from_notion.py -- see scripts/README.md."
            )

    if args.report:
        with open(args.report, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
